dbt_health_monitor:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: pipeline-health-mon-2026
      dataset: layer
      location: us-central1
      threads: 4
      timeout_seconds: 300
      priority: interactive
      retries: 1
